main:
  project_name: "Yolov5_PV_1st_training"
  experiment_name: "dev"
data_set:
  file_url: "https://drive.google.com/uc?export=download&id=1YQv0o37_LcnLCdzlCjF6yjuPB9jri5Pf"
  artifact_name: "Comal_Alzo_1st_labelledData"
  artifact_type: "Yolov5 Dataset"
  artifact_description: "First labelled dataset from Comal Alzo, a lot of data is still missing!"