main:
  project_name: "Yolov5_PV_1st_training"
  experiment_name: "dev"
data_set:
  file_url: "https://this_does_not_work.html"
  artifact_name: "Comal_Alzo_1st_labelledData"
  artifact_type: "Yolov5 Dataset"
  artifact_description: "First labelled dataset from Comal Alzo, a lot of data is still missing!"