main:
  project_name: "Yolov5_PV_1st_training"
  experiment_name: "dev"
data_set:
  file_url: "https://raw.githubusercontent.com/scikit-learn/scikit-learn/4dfdfb4e1bb3719628753a4ece995a1b2fa5312a/sklearn/datasets/data/iris.csv"
  artifact_name: "Comal_Alzo_1st_labelledData"
  artifact_type: "Yolov5 Dataset"
  artifact_description: "First labelled dataset from Comal Alzo, a lot of data is still missing!"