name: 02_Yolov5_training
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - gitpython>=3.1.30
  - matplotlib>=3.3
  - numpy>=1.22.2
  - opencv-python>=4.1.1
  - Pillow>=7.1.2
  - psutil  # system resources
  - PyYAML>=5.3.1
  - requests>=2.23.0
  - scipy>=1.4.1
  - thop>=0.1.1  # FLOPs computation
  - torch>=1.8.0  # see https://pytorch.org/get-started/locally (recommended)
  - torchvision>=0.9.0
  - tqdm>=4.64.0
  - ultralytics>=8.0.147
  - protobuf<=3.20.1  # https://github.com/ultralytics/yolov5/issues/8012
  - setuptools>=65.5.1 # Snyk vulnerability fix
  - pip:
      - wandb==0.10.21

